# name: release

# # Run action on every commit to main, release only when requested through commit annotation.
# on:
#   push:
#     branches: [main]

# jobs:
#   build-test-release:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       # - run: npm install
#       # - run: npm run build
#       # - run: npm test
#       - uses: tobua/release-npm-action@v3
#         with:
#           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
